Repository Triumers/KMS-Back, pull requests merged in 2024-05, with the labels that each got.

#5 [Feature] 익명 게시판 기본 기능 구현
  .github/workflows/gpt.yml
  .github/workflows/gradle.yml
  build.gradle
  src/main/java/org/triumers/kmsback/auth/command/Application/controller/AuthController.java
  src/main/java/org/triumers/kmsback/auth/command/Application/dto/AuthDTO.java
  src/main/java/org/triumers/kmsback/auth/command/Application/service/AuthService.java
  src/main/java/org/triumers/kmsback/auth/command/Application/service/AuthServiceImpl.java
  src/main/java/org/triumers/kmsback/auth/command/domain/aggregate/entity/Auth.java
  src/main/java/org/triumers/kmsback/auth/command/domain/aggregate/enums/UserRole.java
  src/main/java/org/triumers/kmsback/auth/command/domain/aggregate/enums/UserRoleConverter.java
  src/main/java/org/triumers/kmsback/auth/command/domain/aggregate/vo/CmdRequestAuthVO.java
  src/main/java/org/triumers/kmsback/auth/command/domain/aggregate/vo/CmdResponseMessageVO.java
  src/main/java/org/triumers/kmsback/auth/command/domain/repository/AuthRepository.java
  src/main/java/org/triumers/kmsback/common/config/SecurityConfig.java
  src/test/java/org/triumers/kmsback/auth/command/Application/service/AuthServiceTest.java
Labels: enhancement

#2 [Feature] Post 기본 기능 구현
  build.gradle
  src/main/java/org/triumers/kmsback/common/config/MyBatisConfig.java
  src/main/java/org/triumers/kmsback/post/command/Application/controller/CmdPostController.java
  src/main/java/org/triumers/kmsback/post/command/Application/dto/CmdFavoritesDTO.java
  src/main/java/org/triumers/kmsback/post/command/Application/dto/CmdJoinEmployeeDTO.java
  src/main/java/org/triumers/kmsback/post/command/Application/dto/CmdLikeDTO.java
  src/main/java/org/triumers/kmsback/post/command/Application/dto/CmdPostAndTagsDTO.java
  src/main/java/org/triumers/kmsback/post/command/Application/dto/CmdPostDTO.java
  src/main/java/org/triumers/kmsback/post/command/Application/dto/CmdTabRelationDTO.java
  src/main/java/org/triumers/kmsback/post/command/Application/dto/CmdTagDTO.java
  src/main/java/org/triumers/kmsback/post/command/Application/service/CmdPostService.java
  src/main/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceImpl.java
  src/main/java/org/triumers/kmsback/post/command/Application/service/CmdTabService.java
  src/main/java/org/triumers/kmsback/post/command/Application/service/CmdTabServiceImpl.java
  src/main/java/org/triumers/kmsback/post/command/domain/aggregate/entity/CmdFavorites.java
  src/main/java/org/triumers/kmsback/post/command/domain/aggregate/entity/CmdJoinEmployee.java
  src/main/java/org/triumers/kmsback/post/command/domain/aggregate/entity/CmdLike.java
  src/main/java/org/triumers/kmsback/post/command/domain/aggregate/entity/CmdPost.java
  src/main/java/org/triumers/kmsback/post/command/domain/aggregate/entity/CmdPostTag.java
  src/main/java/org/triumers/kmsback/post/command/domain/aggregate/entity/CmdTabBottom.java
  src/main/java/org/triumers/kmsback/post/command/domain/aggregate/entity/CmdTabRelation.java
  src/main/java/org/triumers/kmsback/post/command/domain/aggregate/entity/CmdTabTop.java
  src/main/java/org/triumers/kmsback/post/command/domain/aggregate/entity/CmdTag.java
  src/main/java/org/triumers/kmsback/post/command/domain/aggregate/vo/CmdRequestPost.java
  src/main/java/org/triumers/kmsback/post/command/domain/aggregate/vo/CmdResponseMessageVO.java
  src/main/java/org/triumers/kmsback/post/command/domain/aggregate/vo/CmdTagVO.java
  src/main/java/org/triumers/kmsback/post/command/domain/repository/CmdFavoritesRepository.java
  src/main/java/org/triumers/kmsback/post/command/domain/repository/CmdJoinEmployeeRepository.java
  src/main/java/org/triumers/kmsback/post/command/domain/repository/CmdLikeRepository.java
  src/main/java/org/triumers/kmsback/post/command/domain/repository/CmdPostRepository.java
  src/main/java/org/triumers/kmsback/post/command/domain/repository/CmdPostTagRepository.java
  src/main/java/org/triumers/kmsback/post/command/domain/repository/CmdTabRelationRepository.java
  src/main/java/org/triumers/kmsback/post/command/domain/repository/CmdTagRepository.java
  src/main/java/org/triumers/kmsback/post/query/aggregate/entity/QryFavorites.java
  src/main/java/org/triumers/kmsback/post/query/aggregate/entity/QryJoinEmployee.java
  src/main/java/org/triumers/kmsback/post/query/aggregate/entity/QryLike.java
  src/main/java/org/triumers/kmsback/post/query/aggregate/entity/QryPost.java
  src/main/java/org/triumers/kmsback/post/query/aggregate/entity/QryPostAndTag.java
  src/main/java/org/triumers/kmsback/post/query/aggregate/entity/QryPostTag.java
  src/main/java/org/triumers/kmsback/post/query/aggregate/entity/QryTabBottom.java
  src/main/java/org/triumers/kmsback/post/query/aggregate/entity/QryTabRelation.java
  src/main/java/org/triumers/kmsback/post/query/aggregate/entity/QryTabTop.java
  src/main/java/org/triumers/kmsback/post/query/aggregate/entity/QryTag.java
  src/main/java/org/triumers/kmsback/post/query/aggregate/vo/QryResponseMessageVO.java
  src/main/java/org/triumers/kmsback/post/query/controller/QryPostController.java
  src/main/java/org/triumers/kmsback/post/query/dto/QryFavoritesDTO.java
  src/main/java/org/triumers/kmsback/post/query/dto/QryJoinEmployeeDTO.java
  src/main/java/org/triumers/kmsback/post/query/dto/QryLikeDTO.java
  src/main/java/org/triumers/kmsback/post/query/dto/QryPostAndTagsDTO.java
  src/main/java/org/triumers/kmsback/post/query/dto/QryPostDTO.java
  src/main/java/org/triumers/kmsback/post/query/dto/QryTabRelationDTO.java
  src/main/java/org/triumers/kmsback/post/query/dto/QryTagDTO.java
  src/main/java/org/triumers/kmsback/post/query/repository/QryPostMapper.java
  src/main/java/org/triumers/kmsback/post/query/service/QryPostService.java
  src/main/java/org/triumers/kmsback/post/query/service/QryPostServiceImpl.java
  src/main/resources/org/triumers/kmsback/post/query/repository/QryPostMapper.xml
  src/test/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceTests.java
  src/test/java/org/triumers/kmsback/post/command/Application/service/CmdTabServiceTests.java
  src/test/java/org/triumers/kmsback/post/query/service/QryPostServiceTest.java
Labels: enhancement

#10 [Feature] 퀴즈 기본 조회 기능
  build.gradle
  src/main/java/org/triumers/kmsback/quiz/query/aggregate/entity/QryQuiz.java
  src/main/java/org/triumers/kmsback/quiz/query/controller/QryQuizController.java
  src/main/java/org/triumers/kmsback/quiz/query/dto/QryQuizDTO.java
  src/main/java/org/triumers/kmsback/quiz/query/repository/QuizMapper.java
  src/main/java/org/triumers/kmsback/quiz/query/service/QryQuizService.java
  src/main/java/org/triumers/kmsback/quiz/query/service/QryQuizServiceImpl.java
  src/main/resources/org/triumers/kmsback/quiz/query/repository/QuizMapper.xml
  src/test/java/org/triumers/kmsback/quiz/query/service/QryQuizServiceImplTest.java
Labels: enhancement

#12 [Feature] 게시글 조회 관련 기능 및 TAB 테스트 수정
  src/main/resources/org/triumers/kmsback/post/query/repository/QryPostMapper.xml
  src/test/java/org/triumers/kmsback/post/command/Application/service/CmdTabServiceTests.java
  src/test/java/org/triumers/kmsback/post/query/service/QryPostServiceTest.java
Labels: bug, enhancement

#15 [Feature] 퀴즈 기본 기능 구현
  src/main/java/org/triumers/kmsback/quiz/command/Application/controller/CmdQuizController.java
  src/main/java/org/triumers/kmsback/quiz/command/Application/dto/CmdQuizDTO.java
  src/main/java/org/triumers/kmsback/quiz/command/Application/service/CmdQuizService.java
  src/main/java/org/triumers/kmsback/quiz/command/Application/service/CmdQuizServiceImpl.java
  src/main/java/org/triumers/kmsback/quiz/command/domain/aggregate/entity/CmdQuiz.java
  src/main/java/org/triumers/kmsback/quiz/command/domain/aggregate/vo/CmdRequestQuizVo.java
  src/main/java/org/triumers/kmsback/quiz/command/domain/aggregate/vo/CmdRequestRemoveQuizVo.java
  src/main/java/org/triumers/kmsback/quiz/command/domain/aggregate/vo/CmdResponseMessageVO.java
  src/main/java/org/triumers/kmsback/quiz/command/domain/repository/CmdQuizRepository.java
  src/main/java/org/triumers/kmsback/quiz/query/aggregate/entity/QryAnswerSubmitter.java
  src/main/java/org/triumers/kmsback/quiz/query/aggregate/entity/QryQuiz.java
  src/main/java/org/triumers/kmsback/quiz/query/controller/QryAnswerSubmitterController.java
  src/main/java/org/triumers/kmsback/quiz/query/controller/QryQuizController.java
  src/main/java/org/triumers/kmsback/quiz/query/dto/QryAnswerSubmitterDTO.java
  src/main/java/org/triumers/kmsback/quiz/query/dto/QryQuizDTO.java
  src/main/java/org/triumers/kmsback/quiz/query/repository/AnswerSubmitterMapper.java
  src/main/java/org/triumers/kmsback/quiz/query/service/QryAnswerSubmitterService.java
  src/main/java/org/triumers/kmsback/quiz/query/service/QryAnswerSubmitterServiceImpl.java
  src/main/java/org/triumers/kmsback/quiz/query/service/QryQuizServiceImpl.java
  src/main/resources/org/triumers/kmsback/quiz/query/repository/AnswerSubmitterMapper.xml
  src/test/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceTests.java
  src/test/java/org/triumers/kmsback/post/command/Application/service/CmdTabServiceTests.java
  src/test/java/org/triumers/kmsback/quiz/command/Application/service/CmdQuizServiceImplTest.java
  src/test/java/org/triumers/kmsback/quiz/query/service/QryAnswerSubmitterServiceImplTest.java
  src/test/java/org/triumers/kmsback/quiz/query/service/QryQuizServiceImplTest.java
Labels: enhancement

#19 [Feature] 비밀번호 변경 기능 구현
  src/main/java/org/triumers/kmsback/auth/command/Application/dto/PasswordDTO.java
  src/main/java/org/triumers/kmsback/auth/command/Application/service/AuthService.java
  src/main/java/org/triumers/kmsback/auth/command/Application/service/AuthServiceImpl.java
  src/main/java/org/triumers/kmsback/common/exception/WrongInputValueException.java
  src/test/java/org/triumers/kmsback/auth/command/Application/service/AuthServiceTest.java
Labels: enhancement

#21 [Feat] POST 컨트롤러 추가 및 게시글 관련 조회 기능 추가
  build.gradle
  src/main/java/org/triumers/kmsback/post/command/Application/controller/CmdPostController.java
  src/main/java/org/triumers/kmsback/post/command/Application/controller/CmdTabController.java
  src/main/java/org/triumers/kmsback/post/command/Application/dto/CmdJoinEmployeeDTO.java
  src/main/java/org/triumers/kmsback/post/command/Application/dto/CmdPostAndTagsDTO.java
  src/main/java/org/triumers/kmsback/post/command/Application/dto/CmdTabRelationDTO.java
  src/main/java/org/triumers/kmsback/post/command/Application/service/CmdPostService.java
  src/main/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceImpl.java
  src/main/java/org/triumers/kmsback/post/command/Application/service/CmdTabService.java
  src/main/java/org/triumers/kmsback/post/command/Application/service/CmdTabServiceImpl.java
  src/main/java/org/triumers/kmsback/post/command/Application/service/NotificationService.java
  src/main/java/org/triumers/kmsback/post/command/domain/aggregate/entity/CmdPost.java
  src/main/java/org/triumers/kmsback/post/query/controller/QryPostController.java
  src/main/java/org/triumers/kmsback/post/query/dto/QryPostAndTagsDTO.java
  src/main/java/org/triumers/kmsback/post/query/repository/QryPostMapper.java
  src/main/java/org/triumers/kmsback/post/query/service/QryPostService.java
  src/main/java/org/triumers/kmsback/post/query/service/QryPostServiceImpl.java
  src/main/resources/org/triumers/kmsback/post/query/repository/QryPostMapper.xml
  src/test/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceTests.java
  src/test/java/org/triumers/kmsback/post/command/Application/service/CmdTabServiceTests.java
  src/test/java/org/triumers/kmsback/post/query/service/QryPostServiceTest.java
Labels: bug, enhancement

#25 [Refactor] DB수정에 따른 퀴즈 기능 수정
  src/main/java/org/triumers/kmsback/quiz/command/Application/dto/CmdQuizDTO.java
  src/main/java/org/triumers/kmsback/quiz/command/Application/service/CmdQuizServiceImpl.java
  src/main/java/org/triumers/kmsback/quiz/command/domain/aggregate/entity/CmdQuiz.java
  src/main/java/org/triumers/kmsback/quiz/command/domain/aggregate/vo/CmdRequestQuizVo.java
  src/main/java/org/triumers/kmsback/quiz/query/aggregate/entity/QryQuiz.java
  src/main/java/org/triumers/kmsback/quiz/query/dto/QryQuizDTO.java
  src/main/java/org/triumers/kmsback/quiz/query/service/QryQuizServiceImpl.java
  src/main/resources/org/triumers/kmsback/quiz/query/repository/QuizMapper.xml
  src/test/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceTests.java
  src/test/java/org/triumers/kmsback/post/command/Application/service/CmdTabServiceTests.java
  src/test/java/org/triumers/kmsback/post/query/service/QryPostServiceTest.java
  src/test/java/org/triumers/kmsback/quiz/query/service/QryAnswerSubmitterServiceImplTest.java
  src/test/java/org/triumers/kmsback/quiz/query/service/QryQuizServiceImplTest.java
Labels: bug

#22 [Feature] 게시글 관련 기능 수정
  src/main/java/org/triumers/kmsback/common/config/OpenAIConfig.java
  src/main/java/org/triumers/kmsback/post/command/Application/controller/CmdPostController.java
  src/main/java/org/triumers/kmsback/post/command/Application/controller/CmdTabController.java
  src/main/java/org/triumers/kmsback/post/command/Application/dto/ChatGPTRequestDTO.java
  src/main/java/org/triumers/kmsback/post/command/Application/dto/ChatGPTResponseDTO.java
  src/main/java/org/triumers/kmsback/post/command/Application/dto/CmdPostAndTagsDTO.java
  src/main/java/org/triumers/kmsback/post/command/Application/dto/CmdPostDTO.java
  src/main/java/org/triumers/kmsback/post/command/Application/dto/CmdTabDTO.java
  src/main/java/org/triumers/kmsback/post/command/Application/dto/CmdTabRelationDTO.java
  src/main/java/org/triumers/kmsback/post/command/Application/dto/Message.java
  src/main/java/org/triumers/kmsback/post/command/Application/service/CmdPostService.java
  src/main/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceImpl.java
  src/main/java/org/triumers/kmsback/post/command/Application/service/CmdTabService.java
  src/main/java/org/triumers/kmsback/post/command/Application/service/CmdTabServiceImpl.java
  src/main/java/org/triumers/kmsback/post/command/Application/service/OpenAIService.java
  src/main/java/org/triumers/kmsback/post/command/Application/service/OpenAIServiceImpl.java
  src/main/java/org/triumers/kmsback/post/command/domain/aggregate/entity/CmdPost.java
  src/main/java/org/triumers/kmsback/post/command/domain/aggregate/entity/CmdTabBottom.java
  src/main/java/org/triumers/kmsback/post/command/domain/aggregate/entity/CmdTabRelation.java
  src/main/java/org/triumers/kmsback/post/command/domain/aggregate/entity/CmdTabTop.java
  src/main/java/org/triumers/kmsback/post/command/domain/repository/CmdTabBottomRepository.java
  src/main/java/org/triumers/kmsback/post/command/domain/repository/CmdTabTopRepository.java
  src/main/java/org/triumers/kmsback/post/command/domain/repository/CmdTagRepository.java
  src/main/java/org/triumers/kmsback/post/query/aggregate/entity/QryPost.java
  src/main/java/org/triumers/kmsback/post/query/aggregate/entity/QryPostAndTag.java
  src/main/java/org/triumers/kmsback/post/query/aggregate/vo/QryRequestPost.java
  src/main/java/org/triumers/kmsback/post/query/controller/QryPostController.java
  src/main/java/org/triumers/kmsback/post/query/dto/QryPostAndTagsDTO.java
  src/main/java/org/triumers/kmsback/post/query/dto/QryPostDTO.java
  src/main/java/org/triumers/kmsback/post/query/repository/QryPostMapper.java
  src/main/java/org/triumers/kmsback/post/query/service/QryPostService.java
  src/main/java/org/triumers/kmsback/post/query/service/QryPostServiceImpl.java
  src/main/resources/org/triumers/kmsback/post/query/repository/QryPostMapper.xml
  src/test/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceTests.java
  src/test/java/org/triumers/kmsback/post/command/Application/service/CmdTabServiceTests.java
  src/test/java/org/triumers/kmsback/post/query/service/QryPostServiceTest.java
Labels: enhancement

#24 [Feature] 그룹 조회 기능
  src/main/java/org/triumers/kmsback/group/query/controller/QryGroupController.java
  src/main/java/org/triumers/kmsback/group/query/dto/QryGroupDTO.java
  src/main/java/org/triumers/kmsback/group/query/repository/GroupMapper.java
  src/main/java/org/triumers/kmsback/group/query/service/QryGroupService.java
  src/main/java/org/triumers/kmsback/group/query/service/QryGroupServiceImpl.java
  src/main/resources/org/triumers/kmsback/group/query/repository/GroupMapper.xml
  src/test/java/org/triumers/kmsback/group/query/service/QryGroupServiceTest.java
Labels: enhancement

#26 [Feature] tab 서비스 분리
  src/main/java/org/triumers/kmsback/post/command/Application/dto/Message.java
  src/main/java/org/triumers/kmsback/post/command/Application/service/CmdTabService.java
  src/main/java/org/triumers/kmsback/tab/command/Application/controller/CmdTabController.java
  src/main/java/org/triumers/kmsback/tab/command/Application/dto/CmdJoinEmployeeDTO.java
  src/main/java/org/triumers/kmsback/tab/command/Application/dto/CmdTabDTO.java
  src/main/java/org/triumers/kmsback/tab/command/Application/dto/CmdTabRelationDTO.java
  src/main/java/org/triumers/kmsback/tab/command/Application/service/CmdTabService.java
  src/main/java/org/triumers/kmsback/tab/command/Application/service/CmdTabServiceImpl.java
  src/main/java/org/triumers/kmsback/tab/command/domain/aggregate/entity/CmdJoinEmployee.java
  src/main/java/org/triumers/kmsback/tab/command/domain/aggregate/entity/CmdTabBottom.java
  src/main/java/org/triumers/kmsback/tab/command/domain/aggregate/entity/CmdTabRelation.java
  src/main/java/org/triumers/kmsback/tab/command/domain/aggregate/entity/CmdTabTop.java
  src/main/java/org/triumers/kmsback/tab/command/domain/aggregate/vo/CmdResponseMessageVO.java
  src/main/java/org/triumers/kmsback/tab/command/domain/repository/CmdJoinEmployeeRepository.java
  src/main/java/org/triumers/kmsback/tab/command/domain/repository/CmdTabBottomRepository.java
  src/main/java/org/triumers/kmsback/tab/command/domain/repository/CmdTabRelationRepository.java
  src/main/java/org/triumers/kmsback/tab/command/domain/repository/CmdTabTopRepository.java
  src/main/java/org/triumers/kmsback/tab/query/aggregate/entity/QryJoinEmployee.java
  src/main/java/org/triumers/kmsback/tab/query/aggregate/entity/QryTabBottom.java
  src/main/java/org/triumers/kmsback/tab/query/aggregate/entity/QryTabRelation.java
  src/main/java/org/triumers/kmsback/tab/query/aggregate/entity/QryTabTop.java
  src/main/java/org/triumers/kmsback/tab/query/aggregate/vo/QryResponseMessageVO.java
  src/main/java/org/triumers/kmsback/tab/query/dto/QryJoinEmployeeDTO.java
  src/main/java/org/triumers/kmsback/tab/query/dto/QryTabRelationDTO.java
  src/test/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceTests.java
  src/test/java/org/triumers/kmsback/tab/command/Application/service/CmdTabServiceTests.java
Labels: enhancement

#29 [Feature] 내 정보 수정 기능 구현
  src/main/java/org/triumers/kmsback/auth/command/Application/service/AuthService.java
  src/main/java/org/triumers/kmsback/auth/command/Application/service/AuthServiceImpl.java
  src/main/java/org/triumers/kmsback/auth/command/domain/aggregate/entity/Auth.java
  src/main/java/org/triumers/kmsback/common/exception/NotLoginException.java
  src/test/java/org/triumers/kmsback/auth/command/Application/service/AuthServiceTest.java
Labels: enhancement

#30 [Refactor] 토큰 기반 현재 로그인 사용자 조회 private -> public
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/org/triumers/kmsback/auth/command/Application/service/AuthService.java
  src/main/java/org/triumers/kmsback/auth/command/Application/service/AuthServiceImpl.java
Labels: refactor

#32 [Refactor] Auth 값에 대한 검증 Entity -> VO 변경
  build.gradle
  src/main/java/org/triumers/kmsback/auth/command/Application/controller/AuthController.java
  src/main/java/org/triumers/kmsback/auth/command/Application/service/AuthService.java
  src/main/java/org/triumers/kmsback/auth/command/Application/service/AuthServiceImpl.java
  src/main/java/org/triumers/kmsback/auth/command/domain/aggregate/entity/Auth.java
  src/main/java/org/triumers/kmsback/auth/command/domain/aggregate/vo/CmdRequestAuthVO.java
  src/main/java/org/triumers/kmsback/common/exception/GlobalExceptionHandler.java
  src/test/java/org/triumers/kmsback/auth/command/Application/service/AuthServiceTest.java
Labels: refactor

#33 [Feature] 위키 참여자 리스트 기능 추가/태그 변경
  src/main/java/org/triumers/kmsback/common/ai/dto/ChatGPTRequestDTO.java
  src/main/java/org/triumers/kmsback/common/ai/dto/ChatGPTResponseDTO.java
  src/main/java/org/triumers/kmsback/common/ai/dto/Message.java
  src/main/java/org/triumers/kmsback/common/ai/service/OpenAIService.java
  src/main/java/org/triumers/kmsback/common/ai/service/OpenAIServiceImpl.java
  src/main/java/org/triumers/kmsback/post/command/Application/controller/CmdPostController.java
  src/main/java/org/triumers/kmsback/post/command/Application/dto/CmdPostAndTagsDTO.java
  src/main/java/org/triumers/kmsback/post/command/Application/service/CmdPostService.java
  src/main/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceImpl.java
  src/main/java/org/triumers/kmsback/post/command/domain/repository/CmdPostRepository.java
  src/main/java/org/triumers/kmsback/post/query/dto/QryPostAndTagsDTO.java
  src/main/java/org/triumers/kmsback/post/query/repository/QryPostMapper.java
  src/main/java/org/triumers/kmsback/post/query/service/QryPostServiceImpl.java
  src/main/resources/org/triumers/kmsback/post/query/repository/QryPostMapper.xml
  src/test/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceTests.java
  src/test/java/org/triumers/kmsback/post/query/service/QryPostServiceTest.java
Labels: enhancement, refactor

#34 [Feature] 비밀번호 변경, 내 정보 변경 Controller 구현
  src/main/java/org/triumers/kmsback/auth/command/Application/controller/AuthController.java
  src/main/java/org/triumers/kmsback/auth/command/domain/aggregate/vo/CmdRequestAuthVO.java
  src/main/java/org/triumers/kmsback/auth/command/domain/aggregate/vo/CmdRequestEditMyInfoVO.java
  src/main/java/org/triumers/kmsback/auth/command/domain/aggregate/vo/CmdRequestEditPasswordVO.java
  src/main/java/org/triumers/kmsback/common/util/RegularExpression.java
Labels: enhancement, refactor

#35 [Refactor] 테스트용 로그인 유저 메소드 클래스화
  .github/PULL_REQUEST_TEMPLATE.md
  src/test/java/org/triumers/kmsback/auth/command/Application/service/AuthServiceTest.java
  src/test/java/org/triumers/kmsback/common/LoggedInUser.java
  src/test/java/org/triumers/kmsback/common/TestUserInfo.java
Labels: refactor

#36 [Feature/Bug] 일반 게시글 저장 및 수정/권한 확인 함수 오류 수정
  src/main/java/org/triumers/kmsback/common/exception/NotAuthorizedException.java
  src/main/java/org/triumers/kmsback/post/command/Application/controller/CmdPostController.java
  src/main/java/org/triumers/kmsback/post/command/Application/service/CmdPostService.java
  src/main/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceImpl.java
  src/main/java/org/triumers/kmsback/post/command/domain/aggregate/entity/CmdPost.java
  src/main/java/org/triumers/kmsback/post/command/domain/repository/CmdPostRepository.java
  src/main/java/org/triumers/kmsback/post/command/domain/repository/CmdPostTagRepository.java
  src/test/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceTests.java
  src/test/java/org/triumers/kmsback/post/query/service/QryPostServiceTest.java
Labels: bug, enhancement

#37 [Feature] AWS S3 파일 업로드 기능 구현
  build.gradle
  src/main/java/org/triumers/kmsback/common/config/AwsS3Config.java
  src/main/java/org/triumers/kmsback/common/exception/AwsS3Exception.java
  src/main/java/org/triumers/kmsback/common/s3/controller/AwsS3Controller.java
  src/main/java/org/triumers/kmsback/common/s3/service/AwsS3Service.java
  src/main/java/org/triumers/kmsback/common/s3/service/AwsS3ServiceImpl.java
Labels: enhancement

#38 [Feature] 사원 ID로 제출내역 조회
  src/main/java/org/triumers/kmsback/quiz/query/aggregate/entity/QryAnswerSubmitter.java
  src/main/java/org/triumers/kmsback/quiz/query/controller/QryAnswerSubmitterController.java
  src/main/java/org/triumers/kmsback/quiz/query/dto/QryAnswerSubmitterDTO.java
  src/main/java/org/triumers/kmsback/quiz/query/repository/AnswerSubmitterMapper.java
  src/main/java/org/triumers/kmsback/quiz/query/service/QryAnswerSubmitterService.java
  src/main/java/org/triumers/kmsback/quiz/query/service/QryAnswerSubmitterServiceImpl.java
  src/main/resources/org/triumers/kmsback/quiz/query/repository/AnswerSubmitterMapper.xml
  src/test/java/org/triumers/kmsback/quiz/query/service/QryAnswerSubmitterServiceImplTest.java
Labels: enhancement

#39 [Feature] 결재 기본 기능 구현
  src/main/java/org/triumers/kmsback/approval/command/Application/controller/CmdRequestApprovalController.java
  src/main/java/org/triumers/kmsback/approval/command/Application/dto/CmdApprovalRequestDTO.java
  src/main/java/org/triumers/kmsback/approval/command/Application/dto/CmdRequestApprovalDTO.java
  src/main/java/org/triumers/kmsback/approval/command/Application/service/CmdApprovalTypeService.java
  src/main/java/org/triumers/kmsback/approval/command/Application/service/CmdApprovalTypeServiceImpl.java
  src/main/java/org/triumers/kmsback/approval/command/Application/service/CmdRequestApprovalService.java
  src/main/java/org/triumers/kmsback/approval/command/Application/service/CmdRequestApprovalServiceImpl.java
  src/main/java/org/triumers/kmsback/approval/command/domain/aggregate/entity/CmdApproval.java
  src/main/java/org/triumers/kmsback/approval/command/domain/aggregate/entity/CmdApprovalType.java
  src/main/java/org/triumers/kmsback/approval/command/domain/aggregate/entity/CmdRequestApproval.java
  src/main/java/org/triumers/kmsback/approval/command/domain/repository/CmdApprovalRepository.java
  src/main/java/org/triumers/kmsback/approval/command/domain/repository/CmdApprovalTypeRepository.java
  src/main/java/org/triumers/kmsback/approval/command/domain/repository/CmdRequestApprovalRepository.java
  src/main/java/org/triumers/kmsback/approval/query/aggregate/entity/QryApproval.java
  src/main/java/org/triumers/kmsback/approval/query/aggregate/entity/QryApprovalType.java
  src/main/java/org/triumers/kmsback/approval/query/aggregate/entity/QryRequestApproval.java
  src/main/java/org/triumers/kmsback/approval/query/aggregate/entity/QryTabBottom.java
  src/main/java/org/triumers/kmsback/approval/query/aggregate/entity/QryTabRelation.java
  src/main/java/org/triumers/kmsback/approval/query/aggregate/entity/QryTabTop.java
  src/main/java/org/triumers/kmsback/approval/query/controller/QryRequestApprovalController.java
  src/main/java/org/triumers/kmsback/approval/query/dto/QryRequestApprovalInfoDTO.java
  src/main/java/org/triumers/kmsback/approval/query/dto/QryRequestApprovalWithEmployeeDTO.java
  src/main/java/org/triumers/kmsback/approval/query/repository/QryRequestApprovalMapper.java
  src/main/java/org/triumers/kmsback/approval/query/service/QryRequestApprovalService.java
  src/main/java/org/triumers/kmsback/approval/query/service/QryRequestApprovalServiceImpl.java
  src/main/java/org/triumers/kmsback/employee/command/Application/service/CmdEmployeeService.java
  src/main/resources/org/triumers/kmsback/approval/query/repository/QryRequestApprovalMapper.xml
  src/test/java/org/triumers/kmsback/approval/command/Application/service/CmdApprovalTypeServiceImplTests.java
  src/test/java/org/triumers/kmsback/approval/command/Application/service/CmdRequestApprovalServiceImplTests.java
  src/test/java/org/triumers/kmsback/approval/query/service/QryRequestApprovalServiceImplTests.java
Labels: enhancement

#42 [Feature] 게시글 번역 기능 구현
  build.gradle
  src/main/java/org/triumers/kmsback/common/translation/controller/PostController.java
  src/main/java/org/triumers/kmsback/common/translation/dto/PostDTO.java
  src/main/java/org/triumers/kmsback/common/translation/entity/Post.java
  src/main/java/org/triumers/kmsback/common/translation/entity/PostCn.java
  src/main/java/org/triumers/kmsback/common/translation/entity/PostEng.java
  src/main/java/org/triumers/kmsback/common/translation/entity/PostJpn.java
  src/main/java/org/triumers/kmsback/common/translation/repository/PostRepository.java
  src/main/java/org/triumers/kmsback/common/translation/service/DeeplService.java
  src/main/java/org/triumers/kmsback/common/translation/service/DeeplServiceImpl.java
  src/main/java/org/triumers/kmsback/common/translation/service/PostService.java
  src/main/java/org/triumers/kmsback/common/translation/service/PostServiceImpl.java
  src/test/java/org/triumers/kmsback/common/translation/service/DeeplServiceImplTests.java
  src/test/java/org/triumers/kmsback/common/translation/service/PostServiceImplTests.java
Labels: enhancement

#43 [Feature] 회원 권한 수정 기능 구현
  src/main/java/org/triumers/kmsback/common/config/SecurityConfig.java
  src/main/java/org/triumers/kmsback/user/command/Application/controller/AuthController.java
  src/main/java/org/triumers/kmsback/user/command/Application/controller/ManagerController.java
  src/main/java/org/triumers/kmsback/user/command/Application/dto/ManageUserDTO.java
  src/main/java/org/triumers/kmsback/user/command/Application/service/AuthService.java
  src/main/java/org/triumers/kmsback/user/command/Application/service/AuthServiceImpl.java
  src/main/java/org/triumers/kmsback/user/command/Application/service/ManagerService.java
  src/main/java/org/triumers/kmsback/user/command/Application/service/ManagerServiceImpl.java
  src/main/java/org/triumers/kmsback/user/command/domain/aggregate/vo/CmdRequestEditUserVO.java
  src/main/java/org/triumers/kmsback/user/command/domain/aggregate/vo/CmdRequestSignupUserVO.java
  src/test/java/org/triumers/kmsback/common/LoggedInUser.java
  src/test/java/org/triumers/kmsback/common/TestUserInfo.java
  src/test/java/org/triumers/kmsback/user/command/Application/service/EmployeeServiceTest.java
  src/test/java/org/triumers/kmsback/user/command/Application/service/ManagerServiceTest.java
Labels: enhancement

#44 [Style] postImg 추가 및 관련 기능 코드 수정
  src/main/java/org/triumers/kmsback/post/command/Application/dto/CmdPostAndTagsDTO.java
  src/main/java/org/triumers/kmsback/post/command/Application/dto/CmdPostDTO.java
  src/main/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceImpl.java
  src/main/java/org/triumers/kmsback/post/command/domain/aggregate/entity/CmdPost.java
  src/main/java/org/triumers/kmsback/post/query/aggregate/entity/QryPost.java
  src/main/java/org/triumers/kmsback/post/query/aggregate/entity/QryPostAndTag.java
  src/main/java/org/triumers/kmsback/post/query/dto/QryPostAndTagsDTO.java
  src/main/java/org/triumers/kmsback/post/query/dto/QryPostDTO.java
  src/main/java/org/triumers/kmsback/post/query/service/QryPostServiceImpl.java
  src/main/resources/org/triumers/kmsback/post/query/repository/QryPostMapper.xml
  src/test/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceTests.java
  src/test/java/org/triumers/kmsback/post/query/service/QryPostServiceTest.java
Labels: enhancement, refactor

#45 [Feature] 자신의 권한 이하 계정 비밀번호 초기화 기능 구현
  src/main/java/org/triumers/kmsback/user/command/Application/controller/ManagerController.java
  src/main/java/org/triumers/kmsback/user/command/Application/service/ManagerService.java
  src/main/java/org/triumers/kmsback/user/command/Application/service/ManagerServiceImpl.java
  src/test/java/org/triumers/kmsback/user/command/Application/service/ManagerServiceTest.java
Labels: enhancement

#47 [Refactor] 익명게시판 기능 관련 코드 수정
  src/main/java/org/triumers/kmsback/anonymousboard/command/Application/controller/CmdAnonymousBoardCommentController.java
  src/main/java/org/triumers/kmsback/anonymousboard/command/Application/dto/CmdAnonymousBoardCommentDTO.java
  src/main/java/org/triumers/kmsback/anonymousboard/command/Application/dto/CmdAnonymousBoardDTO.java
  src/main/java/org/triumers/kmsback/anonymousboard/command/Application/service/CmdAnonymousBoardCommentService.java
  src/main/java/org/triumers/kmsback/anonymousboard/command/Application/service/CmdAnonymousBoardCommentServiceImpl.java
  src/main/java/org/triumers/kmsback/anonymousboard/command/Application/service/CmdAnonymousBoardService.java
  src/main/java/org/triumers/kmsback/anonymousboard/command/Application/service/CmdAnonymousBoardServiceImpl.java
  src/main/java/org/triumers/kmsback/anonymousboard/command/domain/aggregate/entity/CmdAnonymousBoard.java
  src/main/java/org/triumers/kmsback/anonymousboard/command/domain/aggregate/entity/CmdAnonymousBoardComment.java
  src/main/java/org/triumers/kmsback/anonymousboard/command/domain/repository/CmdAnonymousBoardCommentRepository.java
  src/main/java/org/triumers/kmsback/anonymousboard/command/domain/repository/CmdAnonymousBoardRepository.java
  src/main/java/org/triumers/kmsback/anonymousboard/query/controller/QryAnonymousBoardCommentController.java
  src/main/java/org/triumers/kmsback/anonymousboard/query/controller/QryAnonymousBoardController.java
  src/main/java/org/triumers/kmsback/anonymousboard/query/dto/QryAnonymousBoardCommentDTO.java
  src/main/java/org/triumers/kmsback/anonymousboard/query/dto/QryAnonymousBoardDTO.java
  src/main/java/org/triumers/kmsback/anonymousboard/query/service/QryAnonymousBoardCommentServiceImpl.java
  src/main/java/org/triumers/kmsback/anonymousboard/query/service/QryAnonymousBoardService.java
  src/main/java/org/triumers/kmsback/anonymousboard/query/service/QryAnonymousBoardServiceImpl.java
  src/main/resources/org/triumers/kmsback/anonymousboard/query/repository/QryAnonymousBoardCommentMapper.xml
  src/main/resources/org/triumers/kmsback/anonymousboard/query/repository/QryAnonymousBoardMapper.xml
  src/test/java/org/triumers/kmsback/anonymousboard/command/Application/controller/CmdAnonymousBoardCommentControllerTests.java
  src/test/java/org/triumers/kmsback/anonymousboard/command/Application/controller/CmdAnonymousBoardControllerTests.java
  src/test/java/org/triumers/kmsback/anonymousboard/command/Application/service/CmdAnonymousBoardCommentServiceImplTests.java
  src/test/java/org/triumers/kmsback/anonymousboard/command/Application/service/CmdAnonymousBoardServiceImplTests.java
  src/test/java/org/triumers/kmsback/anonymousboard/query/controller/QryAnonymousBoardCommentControllerTests.java
  src/test/java/org/triumers/kmsback/anonymousboard/query/controller/QryAnonymousBoardControllerTests.java
  src/test/java/org/triumers/kmsback/anonymousboard/query/service/QryAnonymousBoardCommentServiceImplTests.java
  src/test/java/org/triumers/kmsback/anonymousboard/query/service/QryAnonymousBoardServiceImplTests.java
Labels: bug, refactor

#48 [Feature] 하위 직원 정보 수정 기능 구현
  src/main/java/org/triumers/kmsback/user/command/Application/controller/ManagerController.java
  src/main/java/org/triumers/kmsback/user/command/Application/service/ManagerService.java
  src/main/java/org/triumers/kmsback/user/command/Application/service/ManagerServiceImpl.java
  src/main/java/org/triumers/kmsback/user/command/domain/aggregate/entity/Employee.java
  src/test/java/org/triumers/kmsback/user/command/Application/service/ManagerServiceTest.java
Labels: enhancement

#49 [Feature] 결재 조회 관련 기능 추가 및 코드 수정
  src/main/java/org/triumers/kmsback/approval/command/Application/controller/CmdRequestApprovalController.java
  src/main/java/org/triumers/kmsback/approval/command/Application/dto/CmdRequestApprovalDTO.java
  src/main/java/org/triumers/kmsback/approval/command/Application/service/CmdRequestApprovalService.java
  src/main/java/org/triumers/kmsback/approval/command/Application/service/CmdRequestApprovalServiceImpl.java
  src/main/java/org/triumers/kmsback/approval/command/domain/aggregate/entity/CmdApproval.java
  src/main/java/org/triumers/kmsback/approval/query/aggregate/entity/QryApproval.java
  src/main/java/org/triumers/kmsback/approval/query/aggregate/entity/QryTabBottom.java
  src/main/java/org/triumers/kmsback/approval/query/aggregate/entity/QryTabRelation.java
  src/main/java/org/triumers/kmsback/approval/query/aggregate/entity/QryTabTop.java
  src/main/java/org/triumers/kmsback/approval/query/controller/QryRequestApprovalController.java
  src/main/java/org/triumers/kmsback/approval/query/dto/QryRequestApprovalInfoDTO.java
  src/main/java/org/triumers/kmsback/approval/query/repository/QryRequestApprovalMapper.java
  src/main/java/org/triumers/kmsback/approval/query/service/QryRequestApprovalService.java
  src/main/java/org/triumers/kmsback/approval/query/service/QryRequestApprovalServiceImpl.java
  src/main/resources/org/triumers/kmsback/approval/query/repository/QryRequestApprovalMapper.xml
  src/test/java/org/triumers/kmsback/approval/command/Application/service/CmdRequestApprovalServiceImplTests.java
  src/test/java/org/triumers/kmsback/approval/query/service/QryRequestApprovalServiceImplTests.java
Labels: bug, enhancement

#50 [Feature] 초기 비밀번호 로그인 시 처리 구현
  src/main/java/org/triumers/kmsback/common/auth/LoginFilter.java
  src/main/java/org/triumers/kmsback/common/config/SecurityConfig.java
Labels: enhancement

#46 [Refactor] AI prompt 형식 수정/컨트롤러 추가
  src/main/java/org/triumers/kmsback/common/ai/service/OpenAIService.java
  src/main/java/org/triumers/kmsback/common/ai/service/OpenAIServiceImpl.java
  src/main/java/org/triumers/kmsback/post/command/Application/controller/CmdPostController.java
  src/main/java/org/triumers/kmsback/post/command/Application/service/CmdPostService.java
  src/main/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceImpl.java
  src/main/java/org/triumers/kmsback/post/command/Application/service/NotificationService.java
  src/main/java/org/triumers/kmsback/post/command/domain/aggregate/vo/CmdRequestPostAI.java
  src/main/java/org/triumers/kmsback/post/query/service/QryPostServiceImpl.java
  src/main/java/org/triumers/kmsback/tab/command/Application/controller/CmdTabController.java
  src/main/java/org/triumers/kmsback/tab/command/Application/service/CmdTabService.java
  src/main/java/org/triumers/kmsback/tab/command/Application/service/CmdTabServiceImpl.java
  src/main/java/org/triumers/kmsback/tab/command/domain/repository/CmdTabBottomRepository.java
  src/main/java/org/triumers/kmsback/tab/command/domain/repository/CmdTabRelationRepository.java
  src/main/java/org/triumers/kmsback/tab/command/domain/repository/CmdTabTopRepository.java
  src/test/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceTests.java
  src/test/java/org/triumers/kmsback/tab/command/Application/service/CmdTabServiceTests.java
Labels: enhancement, refactor

#53 [Feature] 본부, 부서, 팀 기본적인 CRUD 구현
  src/main/java/org/triumers/kmsback/organization/command/Application/dto/CmdCenterDTO.java
  src/main/java/org/triumers/kmsback/organization/command/Application/dto/CmdDepartmentDTO.java
  src/main/java/org/triumers/kmsback/organization/command/Application/dto/CmdTeamDTO.java
  src/main/java/org/triumers/kmsback/organization/command/Application/service/CmdCenterService.java
  src/main/java/org/triumers/kmsback/organization/command/Application/service/CmdCenterServiceImpl.java
  src/main/java/org/triumers/kmsback/organization/command/Application/service/CmdDepartmentService.java
  src/main/java/org/triumers/kmsback/organization/command/Application/service/CmdDepartmentServiceImpl.java
  src/main/java/org/triumers/kmsback/organization/command/Application/service/CmdTeamService.java
  src/main/java/org/triumers/kmsback/organization/command/Application/service/CmdTeamServiceImpl.java
  src/main/java/org/triumers/kmsback/organization/command/domain/aggregate/entity/CmdCenter.java
  src/main/java/org/triumers/kmsback/organization/command/domain/aggregate/entity/CmdDepartment.java
  src/main/java/org/triumers/kmsback/organization/command/domain/aggregate/entity/CmdTeam.java
  src/main/java/org/triumers/kmsback/organization/command/domain/repository/CenterRepository.java
  src/main/java/org/triumers/kmsback/organization/command/domain/repository/DepartmentRepository.java
  src/main/java/org/triumers/kmsback/organization/command/domain/repository/TeamRepository.java
  src/main/java/org/triumers/kmsback/organization/query/aggregate/entity/QryCenter.java
  src/main/java/org/triumers/kmsback/organization/query/aggregate/entity/QryDepartment.java
  src/main/java/org/triumers/kmsback/organization/query/aggregate/entity/QryTeam.java
  src/main/java/org/triumers/kmsback/organization/query/dto/QryCenterDTO.java
  src/main/java/org/triumers/kmsback/organization/query/dto/QryDepartmentDTO.java
  src/main/java/org/triumers/kmsback/organization/query/dto/QryTeamDTO.java
  src/main/java/org/triumers/kmsback/organization/query/repository/OrganizationMapper.java
  src/main/java/org/triumers/kmsback/organization/query/service/QryCenterService.java
  src/main/java/org/triumers/kmsback/organization/query/service/QryCenterServiceImpl.java
  src/main/java/org/triumers/kmsback/organization/query/service/QryDepartmentService.java
  src/main/java/org/triumers/kmsback/organization/query/service/QryDepartmentServiceImpl.java
  src/main/java/org/triumers/kmsback/organization/query/service/QryTeamService.java
  src/main/java/org/triumers/kmsback/organization/query/service/QryTeamServiceImpl.java
  src/main/resources/org/triumers/kmsback/organization/query/repository/OrganizationMapper.xml
  src/test/java/org/triumers/kmsback/organization/command/Application/service/CmdCenterServiceTest.java
  src/test/java/org/triumers/kmsback/organization/command/Application/service/CmdDepartmentServiceTest.java
  src/test/java/org/triumers/kmsback/organization/command/Application/service/CmdTeamServiceTest.java
  src/test/java/org/triumers/kmsback/organization/query/service/QryCenterServiceTest.java
  src/test/java/org/triumers/kmsback/organization/query/service/QryDepartmentServiceTest.java
  src/test/java/org/triumers/kmsback/organization/query/service/QryTeamServiceTest.java
Labels: enhancement

#52 [Feature] quiz mapper 수정 및 PathVariable 추가
  src/main/java/org/triumers/kmsback/quiz/query/controller/QryAnswerSubmitterController.java
  src/main/java/org/triumers/kmsback/quiz/query/controller/QryQuizController.java
  src/main/resources/org/triumers/kmsback/quiz/query/repository/AnswerSubmitterMapper.xml
  src/main/resources/org/triumers/kmsback/quiz/query/repository/QuizMapper.xml
  src/test/java/org/triumers/kmsback/KmsBackApplicationTests.java
Labels: bug, refactor

#55 [Feature] 직급, 직책 CRUD 기능 구현
  src/main/java/org/triumers/kmsback/common/config/SecurityConfig.java
  src/main/java/org/triumers/kmsback/common/s3/service/AwsS3ServiceImpl.java
  src/main/java/org/triumers/kmsback/user/command/Application/controller/CmdDutyController.java
  src/main/java/org/triumers/kmsback/user/command/Application/dto/CmdPositionDTO.java
  src/main/java/org/triumers/kmsback/user/command/Application/dto/CmdRankDTO.java
  src/main/java/org/triumers/kmsback/user/command/Application/service/CmdDutyService.java
  src/main/java/org/triumers/kmsback/user/command/Application/service/CmdDutyServiceImpl.java
  src/main/java/org/triumers/kmsback/user/command/domain/aggregate/entity/CmdPosition.java
  src/main/java/org/triumers/kmsback/user/command/domain/aggregate/entity/CmdRank.java
  src/main/java/org/triumers/kmsback/user/command/domain/aggregate/vo/CmdRequestDutyVO.java
  src/main/java/org/triumers/kmsback/user/command/domain/repository/PositionRepository.java
  src/main/java/org/triumers/kmsback/user/command/domain/repository/RankRepository.java
  src/main/java/org/triumers/kmsback/user/query/aggregate/entity/QryPosition.java
  src/main/java/org/triumers/kmsback/user/query/aggregate/entity/QryRank.java
  src/main/java/org/triumers/kmsback/user/query/aggregate/vo/QryPositionVO.java
  src/main/java/org/triumers/kmsback/user/query/aggregate/vo/QryRankVO.java
  src/main/java/org/triumers/kmsback/user/query/aggregate/vo/QryResponsePositionListVO.java
  src/main/java/org/triumers/kmsback/user/query/aggregate/vo/QryResponseRankListVO.java
  src/main/java/org/triumers/kmsback/user/query/controller/QryDutyController.java
  src/main/java/org/triumers/kmsback/user/query/dto/QryPositionDTO.java
  src/main/java/org/triumers/kmsback/user/query/dto/QryRankDTO.java
  src/main/java/org/triumers/kmsback/user/query/repository/DutyMapper.java
  src/main/java/org/triumers/kmsback/user/query/service/QryDutyService.java
  src/main/java/org/triumers/kmsback/user/query/service/QryDutyServiceImpl.java
  src/main/resources/org/triumers/kmsback/user/query/repository/DutyMapper.xml
  src/test/java/org/triumers/kmsback/user/command/Application/service/CmdDutyServiceTest.java
  src/test/java/org/triumers/kmsback/user/query/service/QryDutyServiceTest.java
Labels: enhancement

#56 [Feature] 게시글 ID로 퀴즈 조회
  src/main/java/org/triumers/kmsback/quiz/query/controller/QryQuizController.java
  src/main/java/org/triumers/kmsback/quiz/query/repository/QuizMapper.java
  src/main/java/org/triumers/kmsback/quiz/query/service/QryQuizService.java
  src/main/java/org/triumers/kmsback/quiz/query/service/QryQuizServiceImpl.java
  src/main/resources/org/triumers/kmsback/quiz/query/repository/QuizMapper.xml
  src/test/java/org/triumers/kmsback/quiz/query/service/QryQuizServiceImplTest.java
Labels: enhancement

#57 [Feature] 게시글 조회 시, 좋아요 리스트 추가
  src/main/java/org/triumers/kmsback/post/command/Application/controller/CmdPostController.java
  src/main/java/org/triumers/kmsback/post/command/Application/dto/CmdPostDTO.java
  src/main/java/org/triumers/kmsback/post/command/domain/aggregate/vo/CmdRequestPost.java
  src/main/java/org/triumers/kmsback/post/query/aggregate/entity/QryPost.java
  src/main/java/org/triumers/kmsback/post/query/aggregate/entity/QryPostAndTag.java
  src/main/java/org/triumers/kmsback/post/query/controller/QryPostController.java
  src/main/java/org/triumers/kmsback/post/query/dto/QryPostAndTagsDTO.java
  src/main/java/org/triumers/kmsback/post/query/dto/QryPostDTO.java
  src/main/java/org/triumers/kmsback/post/query/service/QryPostServiceImpl.java
  src/main/java/org/triumers/kmsback/tab/command/Application/controller/CmdTabController.java
  src/main/resources/org/triumers/kmsback/post/query/repository/QryPostMapper.xml
Labels: bug, enhancement, refactor

#58 [Refactor] 익명게시판 테스트 코드 수정 및 페이징 처리
  src/main/java/org/triumers/kmsback/anonymousboard/query/service/QryAnonymousBoardServiceImpl.java
  src/test/java/org/triumers/kmsback/anonymousboard/query/service/QryAnonymousBoardCommentServiceImplTests.java
  src/test/java/org/triumers/kmsback/anonymousboard/query/service/QryAnonymousBoardServiceImplTests.java
Labels: bug

#60 [Refactor] 그룹 데이터 값 변경
  src/test/java/org/triumers/kmsback/group/query/service/QryGroupServiceTest.java
Labels: refactor

#59 [Feature] 직원 조회 기능 구현
  src/main/java/org/triumers/kmsback/user/query/aggregate/entity/QryEmployee.java
  src/main/java/org/triumers/kmsback/user/query/dto/QryEmployeeDTO.java
  src/main/java/org/triumers/kmsback/user/query/repository/EmployeeMapper.java
  src/main/java/org/triumers/kmsback/user/query/service/QryEmployeeService.java
  src/main/java/org/triumers/kmsback/user/query/service/QryEmployeeServiceImpl.java
  src/main/resources/org/triumers/kmsback/user/query/repository/EmployeeMapper.xml
  src/test/java/org/triumers/kmsback/user/query/service/QryEmployeeServiceTest.java
Labels: enhancement
