Repository Triumers/KMS-Back, pull requests merged in 2024-06, with the labels that each got.

#61 [Feature] 익명게시판 댓글 개수 반환 기능 구현
  src/main/java/org/triumers/kmsback/anonymousboard/query/controller/QryAnonymousBoardCommentController.java
  src/main/java/org/triumers/kmsback/anonymousboard/query/service/QryAnonymousBoardCommentService.java
  src/main/java/org/triumers/kmsback/anonymousboard/query/service/QryAnonymousBoardCommentServiceImpl.java
  src/test/java/org/triumers/kmsback/anonymousboard/query/service/QryAnonymousBoardCommentServiceImplTests.java
Labels: enhancement

#62 [Feature] 회원이 접근 가능한 전체 게시글에서 검색 및 조회
  src/main/java/org/triumers/kmsback/group/query/repository/GroupMapper.java
  src/main/java/org/triumers/kmsback/group/query/service/QryGroupService.java
  src/main/java/org/triumers/kmsback/group/query/service/QryGroupServiceImpl.java
  src/main/java/org/triumers/kmsback/post/query/aggregate/vo/QryRequestPost.java
  src/main/java/org/triumers/kmsback/post/query/controller/QryPostController.java
  src/main/java/org/triumers/kmsback/post/query/repository/QryPostMapper.java
  src/main/java/org/triumers/kmsback/post/query/service/QryPostService.java
  src/main/java/org/triumers/kmsback/post/query/service/QryPostServiceImpl.java
  src/main/resources/org/triumers/kmsback/group/query/repository/GroupMapper.xml
  src/main/resources/org/triumers/kmsback/post/query/repository/QryPostMapper.xml
  src/test/java/org/triumers/kmsback/post/query/service/QryPostServiceTest.java
Labels: enhancement

#64 [Refactor] 페이징 처리 코드 수정
  src/main/resources/org/triumers/kmsback/anonymousboard/query/repository/QryAnonymousBoardMapper.xml
Labels: bug

#65 [Feature] 사용자 관련 게시글 조회 기능
  src/main/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceImpl.java
  src/main/java/org/triumers/kmsback/post/query/controller/QryPostController.java
  src/main/java/org/triumers/kmsback/post/query/dto/QryPostAndTagsDTO.java
  src/main/java/org/triumers/kmsback/post/query/repository/QryPostMapper.java
  src/main/java/org/triumers/kmsback/post/query/service/QryPostService.java
  src/main/java/org/triumers/kmsback/post/query/service/QryPostServiceImpl.java
  src/main/resources/org/triumers/kmsback/post/query/repository/QryPostMapper.xml
  src/test/java/org/triumers/kmsback/post/query/service/QryPostServiceTest.java
Labels: enhancement

#66 [Feature] 게시글에 대한 댓글 조회, 추가, 수정, 삭제 기능 구현
  src/main/java/org/triumers/kmsback/comment/command/Application/controller/CommentController.java
  src/main/java/org/triumers/kmsback/comment/command/Application/dto/CmdCommentDTO.java
  src/main/java/org/triumers/kmsback/comment/command/Application/service/CommentService.java
  src/main/java/org/triumers/kmsback/comment/command/Application/service/CommentServiceImpl.java
  src/main/java/org/triumers/kmsback/comment/command/Domain/aggregate/entity/CmdComment.java
  src/main/java/org/triumers/kmsback/comment/command/Domain/repository/CommentRepository.java
  src/main/java/org/triumers/kmsback/comment/query/aggregate/entity/QryComment.java
  src/main/java/org/triumers/kmsback/comment/query/controller/QryCommentController.java
  src/main/java/org/triumers/kmsback/comment/query/domain/service/QryCommentService.java
  src/main/java/org/triumers/kmsback/comment/query/domain/service/QryCommentServiceImpl.java
  src/main/java/org/triumers/kmsback/comment/query/repository/CommentMapper.java
  src/main/resources/org/triumers/kmsback/comment/query/repository/CommentMapper.xml
  src/test/java/org/triumers/kmsback/comment/command/Application/service/CmdCommentServiceTest.java
  src/test/java/org/triumers/kmsback/comment/query/service/QryCmdCommentServiceTest.java
Labels: enhancement

#67 [Feature] 내 게시물, 댓글, 즐겨찾기, 좋아요한 게시물 조회 기능 구현
  src/main/java/org/triumers/kmsback/user/query/aggregate/vo/QryResponseDocsVO.java
  src/main/java/org/triumers/kmsback/user/query/controller/QryAuthController.java
  src/main/java/org/triumers/kmsback/user/query/dto/QryDocsDTO.java
  src/main/java/org/triumers/kmsback/user/query/service/QryAuthService.java
  src/main/java/org/triumers/kmsback/user/query/service/QryAuthServiceImpl.java
  src/test/java/org/triumers/kmsback/user/query/service/QryAuthServiceTest.java
Labels: enhancement

#68 [Refactor] 회원이 속한 탭 조회 코드 변경
  src/main/java/org/triumers/kmsback/group/query/controller/QryGroupController.java
  src/main/java/org/triumers/kmsback/group/query/dto/QryGroupDTO.java
  src/main/java/org/triumers/kmsback/group/query/service/QryGroupService.java
  src/main/java/org/triumers/kmsback/group/query/service/QryGroupServiceImpl.java
  src/main/java/org/triumers/kmsback/post/command/Application/controller/CmdPostController.java
  src/main/java/org/triumers/kmsback/post/command/Application/dto/CmdFavoritesDTO.java
  src/main/java/org/triumers/kmsback/post/command/Application/dto/CmdLikeDTO.java
  src/main/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceImpl.java
  src/main/java/org/triumers/kmsback/post/query/controller/QryPostController.java
  src/main/java/org/triumers/kmsback/post/query/dto/QryPostAndTagsDTO.java
  src/main/java/org/triumers/kmsback/post/query/repository/QryPostMapper.java
  src/main/java/org/triumers/kmsback/post/query/service/QryPostService.java
  src/main/java/org/triumers/kmsback/post/query/service/QryPostServiceImpl.java
  src/main/resources/org/triumers/kmsback/post/query/repository/QryPostMapper.xml
  src/test/java/org/triumers/kmsback/group/query/service/QryGroupServiceTest.java
Labels: refactor

#69 [Feature] 직원 조회 Controller 구현
  src/main/java/org/triumers/kmsback/user/query/aggregate/vo/QryRequestEmployeeVO.java
  src/main/java/org/triumers/kmsback/user/query/aggregate/vo/QryResponseEmployeeVO.java
  src/main/java/org/triumers/kmsback/user/query/controller/QryEmployeeController.java
Labels: enhancement

#70 [Deploy] Main에 이벤트 발생 시, 자동 배포 코드 작성 및 Docker 환경파일 생성
  .github/workflows/deploy.yml
  Dockerrun.aws.json
  Procfile
  build.gradle
  elasticbeanstalk/docker-compose.yml
Labels: enhancement, release

#72 [Feature] Google Authenticator 2차 인증 기능 구현
  build.gradle
  src/main/java/org/triumers/kmsback/common/auth/LoginFilter.java
  src/main/java/org/triumers/kmsback/common/auth/authenticator/controller/OTPUserController.java
  src/main/java/org/triumers/kmsback/common/auth/authenticator/service/OTPUserService.java
  src/main/java/org/triumers/kmsback/common/auth/authenticator/service/OTPValidator.java
  src/main/java/org/triumers/kmsback/common/config/SecurityConfig.java
  src/main/java/org/triumers/kmsback/common/controller/StatusCheckController.java
  src/main/java/org/triumers/kmsback/user/command/Application/controller/AuthController.java
  src/main/java/org/triumers/kmsback/user/command/Application/dto/CustomUserDetails.java
  src/main/java/org/triumers/kmsback/user/command/Application/service/AuthService.java
  src/main/java/org/triumers/kmsback/user/command/Application/service/AuthServiceImpl.java
  src/main/java/org/triumers/kmsback/user/command/domain/aggregate/entity/Employee.java
  src/main/java/org/triumers/kmsback/user/command/domain/aggregate/vo/CmdRequestAccountVO.java
  src/main/java/org/triumers/kmsback/user/query/controller/QryAuthController.java
  src/main/java/org/triumers/kmsback/user/query/service/QryAuthService.java
  src/main/java/org/triumers/kmsback/user/query/service/QryAuthServiceImpl.java
  src/test/java/org/triumers/kmsback/user/command/Application/service/CmdAuthServiceTest.java
  src/test/java/org/triumers/kmsback/user/query/service/QryAuthServiceTest.java
Labels: enhancement

#73 [Refactor] 결재 다중 조회, 취소된 결재 조회 구현 및 페이징 처리
  src/main/java/org/triumers/kmsback/approval/command/Application/controller/CmdRequestApprovalController.java
  src/main/java/org/triumers/kmsback/approval/query/controller/QryRequestApprovalController.java
  src/main/java/org/triumers/kmsback/approval/query/dto/QryRequestApprovalInfoDTO.java
  src/main/java/org/triumers/kmsback/approval/query/dto/QryRequestApprovalWithEmployeeDTO.java
  src/main/java/org/triumers/kmsback/approval/query/repository/QryRequestApprovalMapper.java
  src/main/java/org/triumers/kmsback/approval/query/service/QryRequestApprovalService.java
  src/main/java/org/triumers/kmsback/approval/query/service/QryRequestApprovalServiceImpl.java
  src/main/resources/org/triumers/kmsback/approval/query/repository/QryRequestApprovalMapper.xml
  src/test/java/org/triumers/kmsback/approval/query/service/QryRequestApprovalServiceImplTests.java
Labels: enhancement, refactor

#74 [Refactor] 탭/포스트 서비스 및 컨트롤러 수정
  src/main/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceImpl.java
  src/main/java/org/triumers/kmsback/tab/command/Application/controller/CmdTabController.java
Labels: refactor

#75 [Refactor] 페이징 처리에 따른 컨트롤러 수정
  src/main/java/org/triumers/kmsback/post/query/aggregate/vo/QryRequestPost.java
  src/main/java/org/triumers/kmsback/post/query/controller/QryPostController.java
  src/main/resources/org/triumers/kmsback/post/query/repository/QryPostMapper.xml
Labels: refactor

#76 [Fix] 첫 로그인 시 비밀번호 변경 로직에서 토큰 안담기는 문제 개선
  src/main/java/org/triumers/kmsback/common/auth/LoginFilter.java
  src/main/java/org/triumers/kmsback/user/command/Application/controller/AuthController.java
Labels: bug

#77 [Refactor] 퇴사한 직원 포함 조회/Cmd -> Qry 변경
  src/main/java/org/triumers/kmsback/post/query/controller/QryPostController.java
  src/main/java/org/triumers/kmsback/post/query/dto/QryPostAndTagsDTO.java
  src/main/java/org/triumers/kmsback/post/query/service/QryPostService.java
  src/main/java/org/triumers/kmsback/post/query/service/QryPostServiceImpl.java
  src/main/java/org/triumers/kmsback/user/query/controller/QryEmployeeController.java
  src/main/java/org/triumers/kmsback/user/query/repository/EmployeeMapper.java
  src/main/java/org/triumers/kmsback/user/query/service/QryAuthServiceImpl.java
  src/main/java/org/triumers/kmsback/user/query/service/QryEmployeeService.java
  src/main/java/org/triumers/kmsback/user/query/service/QryEmployeeServiceImpl.java
  src/main/resources/org/triumers/kmsback/user/query/repository/EmployeeMapper.xml
  src/test/java/org/triumers/kmsback/post/query/service/QryPostServiceTest.java
Labels: bug, enhancement, refactor

#78 [Feature] 이미지 한정 업로드, 접속 IP확인 기능 구현
  src/main/java/org/triumers/kmsback/common/config/SecurityConfig.java
  src/main/java/org/triumers/kmsback/common/controller/StatusCheckController.java
  src/main/java/org/triumers/kmsback/common/exception/AwsS3Exception.java
  src/main/java/org/triumers/kmsback/common/s3/controller/AwsS3Controller.java
  src/main/java/org/triumers/kmsback/common/s3/service/AwsS3Service.java
  src/main/java/org/triumers/kmsback/common/s3/service/AwsS3ServiceImpl.java
  src/main/java/org/triumers/kmsback/common/util/IpAddressUtil.java
Labels: enhancement, refactor

#80 [Release] 배포 파일 생성 및 기능개선
  build.gradle
  src/main/java/org/triumers/kmsback/common/config/SecurityConfig.java
  src/main/java/org/triumers/kmsback/common/controller/StatusCheckController.java
  src/main/java/org/triumers/kmsback/common/exception/AwsS3Exception.java
  src/main/java/org/triumers/kmsback/common/s3/controller/AwsS3Controller.java
  src/main/java/org/triumers/kmsback/common/s3/service/AwsS3Service.java
  src/main/java/org/triumers/kmsback/common/s3/service/AwsS3ServiceImpl.java
  src/main/java/org/triumers/kmsback/common/util/IpAddressUtil.java
  src/main/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceImpl.java
  src/main/java/org/triumers/kmsback/post/command/Application/service/NotificationService.java
  src/main/java/org/triumers/kmsback/user/query/controller/QryEmployeeController.java
Labels: enhancement, refactor

#81 [Fix] 에러 처리 구현
  src/main/java/org/triumers/kmsback/quiz/query/controller/QryQuizController.java
  src/main/java/org/triumers/kmsback/quiz/query/service/QryQuizServiceImpl.java
Labels: bug

#82 [Fix] 에러 처리 배포
  src/main/java/org/triumers/kmsback/quiz/query/controller/QryQuizController.java
  src/main/java/org/triumers/kmsback/quiz/query/service/QryQuizServiceImpl.java
Labels: bug, release

#83 [Refactor] 게시글 삭제 시 해당 게시글의 댓글까지 삭제되게 수정
  src/main/java/org/triumers/kmsback/anonymousboard/command/Application/service/CmdAnonymousBoardServiceImpl.java
  src/main/java/org/triumers/kmsback/anonymousboard/command/domain/aggregate/entity/CmdAnonymousBoard.java
  src/main/java/org/triumers/kmsback/approval/command/Application/dto/CmdApprovalRequestDTO.java
  src/test/java/org/triumers/kmsback/anonymousboard/command/Application/service/CmdAnonymousBoardCommentServiceImplTests.java
  src/test/java/org/triumers/kmsback/anonymousboard/command/Application/service/CmdAnonymousBoardServiceImplTests.java
  src/test/java/org/triumers/kmsback/anonymousboard/query/service/QryAnonymousBoardCommentServiceImplTests.java
  src/test/java/org/triumers/kmsback/anonymousboard/query/service/QryAnonymousBoardServiceImplTests.java
Labels: bug, refactor

#84 [Feature] 외부망 접속 시 2차 인증 요구 기능 구현
  src/main/java/org/triumers/kmsback/common/auth/LoginFilter.java
  src/main/java/org/triumers/kmsback/user/command/Application/controller/AuthController.java
Labels: enhancement

#85 [Release] 배포 파일 생성 및 기능개선
  src/main/java/org/triumers/kmsback/anonymousboard/command/Application/service/CmdAnonymousBoardServiceImpl.java
  src/main/java/org/triumers/kmsback/anonymousboard/command/domain/aggregate/entity/CmdAnonymousBoard.java
  src/main/java/org/triumers/kmsback/approval/command/Application/dto/CmdApprovalRequestDTO.java
  src/main/java/org/triumers/kmsback/common/auth/LoginFilter.java
  src/main/java/org/triumers/kmsback/user/command/Application/controller/AuthController.java
  src/test/java/org/triumers/kmsback/anonymousboard/command/Application/service/CmdAnonymousBoardCommentServiceImplTests.java
  src/test/java/org/triumers/kmsback/anonymousboard/command/Application/service/CmdAnonymousBoardServiceImplTests.java
  src/test/java/org/triumers/kmsback/anonymousboard/query/service/QryAnonymousBoardCommentServiceImplTests.java
  src/test/java/org/triumers/kmsback/anonymousboard/query/service/QryAnonymousBoardServiceImplTests.java
Labels: bug, enhancement, refactor

#86 [Fix] IP 검증 문제로 인한 2차인증 없는 계정 로그인 불가 에러 임시 조치
  src/main/java/org/triumers/kmsback/common/auth/LoginFilter.java
Labels: bug

#87 [Fix] 외부망 접속 시 2차 인증 버그 수정
  src/main/java/org/triumers/kmsback/common/auth/LoginFilter.java
Labels: bug

#88 [Fix] 외부망 접속 시 2차 인증 버그 수정위한 컨트롤러
  src/main/java/org/triumers/kmsback/common/controller/StatusCheckController.java
Labels: bug, wontfix

#89 [Fix] 임시 프린트문 생성
  src/main/java/org/triumers/kmsback/common/auth/LoginFilter.java
Labels: bug, wontfix

#90 [Fix] 외부망 접속 시 2차 인증 버그 수정
  src/main/java/org/triumers/kmsback/common/auth/LoginFilter.java
Labels: bug, wontfix

#91 [Fix] 외부망 접속 시 2차 인증 버그 수정
  src/main/java/org/triumers/kmsback/user/command/Application/controller/AuthController.java
Labels: bug, wontfix

#92 [Refactor] 회원의 워크스페이스 추가로 조회해오기
  src/main/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceImpl.java
  src/main/java/org/triumers/kmsback/tab/command/Application/service/CmdTabServiceImpl.java
  src/main/java/org/triumers/kmsback/tab/command/domain/repository/CmdTabRelationRepository.java
  src/main/resources/org/triumers/kmsback/group/query/repository/GroupMapper.xml
Labels: bug, refactor

#93 [Fix] 예외 처리 임시 구현
  src/main/java/org/triumers/kmsback/anonymousboard/command/Application/controller/CmdAnonymousBoardCommentController.java
  src/main/java/org/triumers/kmsback/anonymousboard/command/Application/controller/CmdAnonymousBoardController.java
  src/main/java/org/triumers/kmsback/anonymousboard/query/controller/QryAnonymousBoardCommentController.java
  src/main/java/org/triumers/kmsback/anonymousboard/query/controller/QryAnonymousBoardController.java
  src/main/java/org/triumers/kmsback/approval/command/Application/controller/CmdRequestApprovalController.java
  src/main/java/org/triumers/kmsback/approval/query/controller/QryRequestApprovalController.java
  src/main/java/org/triumers/kmsback/comment/command/Application/controller/CommentController.java
  src/main/java/org/triumers/kmsback/comment/query/controller/QryCommentController.java
  src/main/java/org/triumers/kmsback/common/auth/authenticator/controller/OTPUserController.java
  src/main/java/org/triumers/kmsback/common/controller/StatusCheckController.java
  src/main/java/org/triumers/kmsback/common/s3/controller/AwsS3Controller.java
  src/main/java/org/triumers/kmsback/common/translation/controller/PostController.java
  src/main/java/org/triumers/kmsback/group/query/controller/QryGroupController.java
  src/main/java/org/triumers/kmsback/organization/query/controller/OrganizationController.java
  src/main/java/org/triumers/kmsback/post/command/Application/controller/CmdPostController.java
  src/main/java/org/triumers/kmsback/post/query/controller/QryPostController.java
  src/main/java/org/triumers/kmsback/quiz/command/Application/controller/CmdAnswerSubmitterController.java
  src/main/java/org/triumers/kmsback/quiz/command/Application/controller/CmdQuizController.java
  src/main/java/org/triumers/kmsback/quiz/query/controller/QryAnswerSubmitterController.java
  src/main/java/org/triumers/kmsback/tab/command/Application/controller/CmdTabController.java
  src/main/java/org/triumers/kmsback/user/command/Application/controller/AuthController.java
  src/main/java/org/triumers/kmsback/user/command/Application/controller/CmdDutyController.java
  src/main/java/org/triumers/kmsback/user/command/Application/controller/ManagerController.java
  src/main/java/org/triumers/kmsback/user/query/controller/QryDutyController.java
Labels: bug, wontfix

#95 [Bug] 워크스페이스 추가 조회 수정
  src/main/resources/org/triumers/kmsback/group/query/repository/GroupMapper.xml
Labels: bug

#96 [Release] 워크스페이스 버그 수정
  src/main/resources/org/triumers/kmsback/group/query/repository/GroupMapper.xml
Labels: bug, release

#97 [Feature] 댓글 코드 개선
  src/main/java/org/triumers/kmsback/comment/command/Application/controller/CommentController.java
  src/main/java/org/triumers/kmsback/comment/command/Application/service/CommentService.java
  src/main/java/org/triumers/kmsback/comment/command/Application/service/CommentServiceImpl.java
  src/main/java/org/triumers/kmsback/comment/command/Domain/aggregate/entity/CmdComment.java
  src/main/java/org/triumers/kmsback/comment/command/Domain/repository/CommentRepository.java
  src/main/resources/org/triumers/kmsback/comment/query/repository/CommentMapper.xml
  src/test/java/org/triumers/kmsback/comment/command/Application/service/CmdCommentServiceTest.java
  src/test/java/org/triumers/kmsback/common/authenticator/OTPUserServiceTest.java
  src/test/java/org/triumers/kmsback/common/authenticator/OTPValidatorTest.java
Labels: refactor

#98 [Fix] 댓글 예외처리 수정
  src/main/java/org/triumers/kmsback/comment/command/Application/controller/CommentController.java
  src/main/java/org/triumers/kmsback/comment/command/Application/service/CommentService.java
  src/main/java/org/triumers/kmsback/comment/command/Application/service/CommentServiceImpl.java
  src/main/java/org/triumers/kmsback/comment/command/Domain/aggregate/entity/CmdComment.java
  src/main/java/org/triumers/kmsback/comment/command/Domain/repository/CommentRepository.java
  src/main/resources/org/triumers/kmsback/comment/query/repository/CommentMapper.xml
  src/test/java/org/triumers/kmsback/comment/command/Application/service/CmdCommentServiceTest.java
  src/test/java/org/triumers/kmsback/common/authenticator/OTPUserServiceTest.java
  src/test/java/org/triumers/kmsback/common/authenticator/OTPValidatorTest.java
Labels: bug, enhancement, refactor, release

#99 [Fix] nginx 용량 수정
  ebextensions/01_nginx.config
Labels: bug, enhancement, release

#100 [Refactor] Auth 관련 코드 고도화
  src/main/java/org/triumers/kmsback/common/auth/LoginFilter.java
  src/main/java/org/triumers/kmsback/user/command/Application/controller/AuthController.java
  src/main/java/org/triumers/kmsback/user/command/Application/controller/CmdDutyController.java
  src/main/java/org/triumers/kmsback/user/command/Application/controller/ManagerController.java
  src/main/java/org/triumers/kmsback/user/query/controller/QryAuthController.java
  src/main/java/org/triumers/kmsback/user/query/controller/QryDutyController.java
  src/main/java/org/triumers/kmsback/user/query/controller/QryEmployeeController.java
  src/test/java/org/triumers/kmsback/approval/command/Application/service/CmdApprovalTypeServiceImplTests.java
  src/test/java/org/triumers/kmsback/group/query/service/QryGroupServiceTest.java
  src/test/java/org/triumers/kmsback/quiz/command/Application/service/CmdAnswerSubmitterServiceImplTest.java
  src/test/java/org/triumers/kmsback/quiz/command/Application/service/CmdQuizServiceImplTest.java
  src/test/java/org/triumers/kmsback/quiz/query/service/QryQuizServiceImplTest.java
  src/test/java/org/triumers/kmsback/tab/command/Application/service/CmdTabServiceTests.java
Labels: refactor

#101 [Refactor] 테스트 계정 생성 개선
  src/test/java/org/triumers/kmsback/common/LoggedInUser.java
Labels: refactor

#102 [Feature] 관리자 계정 존재하지 않는 경우 자동 계정 생성 기능
  src/main/java/org/triumers/kmsback/common/auth/createAdmin/AdminAccountInitializer.java
  src/test/java/org/triumers/kmsback/common/LoggedInUser.java
Labels: enhancement

#103 [Refactor] Post/Tab 서비스 테스트 코드 변경
  src/main/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceImpl.java
  src/test/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceTests.java
  src/test/java/org/triumers/kmsback/post/query/service/QryPostServiceTest.java
  src/test/java/org/triumers/kmsback/tab/command/Application/service/CmdTabServiceTests.java
Labels: refactor

#104 [Release] 기능 개선 및 버그 수정
  .github/workflows/deploy.yml
  .github/workflows/gpt.yml
  src/main/java/org/triumers/kmsback/common/auth/LoginFilter.java
  src/main/java/org/triumers/kmsback/common/auth/createAdmin/AdminAccountInitializer.java
  src/main/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceImpl.java
  src/main/java/org/triumers/kmsback/user/command/Application/controller/AuthController.java
  src/main/java/org/triumers/kmsback/user/command/Application/controller/CmdDutyController.java
  src/main/java/org/triumers/kmsback/user/command/Application/controller/ManagerController.java
  src/main/java/org/triumers/kmsback/user/query/controller/QryAuthController.java
  src/main/java/org/triumers/kmsback/user/query/controller/QryDutyController.java
  src/main/java/org/triumers/kmsback/user/query/controller/QryEmployeeController.java
  src/test/java/org/triumers/kmsback/approval/command/Application/service/CmdApprovalTypeServiceImplTests.java
  src/test/java/org/triumers/kmsback/common/LoggedInUser.java
  src/test/java/org/triumers/kmsback/group/query/service/QryGroupServiceTest.java
  src/test/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceTests.java
  src/test/java/org/triumers/kmsback/post/query/service/QryPostServiceTest.java
  src/test/java/org/triumers/kmsback/quiz/command/Application/service/CmdAnswerSubmitterServiceImplTest.java
  src/test/java/org/triumers/kmsback/quiz/command/Application/service/CmdQuizServiceImplTest.java
  src/test/java/org/triumers/kmsback/quiz/query/service/QryQuizServiceImplTest.java
  src/test/java/org/triumers/kmsback/tab/command/Application/service/CmdTabServiceTests.java
Labels: bug, enhancement, refactor
